# -*- coding: utf-8 -*-
"""Stock Market Analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qksh4hqC4ZkJCHGIhICJczqDNVF5j5yi
"""



#Given historical stock price data for Apple, Microsoft, Netflix and Google over the past three months, your task is to analyze and compare the performance of these companies in the stock market using various data science techniques.

import pandas as pd
import numpy as np
!pip install seaborn
import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
!pip install matplotlib-venn
import plotly.express as px

df=pd.read_csv("/content/stocks.csv")
df.head(20)

print(df)

df.describe()

df["Ticker"].unique()

df.groupby("Ticker")["Open"].mean()

df.groupby("Ticker")["Close"].mean()

df.groupby("Ticker")["Volume"].mean()

#It provides 50 moving average
df['Open_50_MA'] = df.groupby('Ticker')['Open'].transform(lambda x: x.rolling(window=50).mean())
df['Close_50_MA'] = df.groupby('Ticker')['Close'].transform(lambda x: x.rolling(window=50).mean())
df['General_50_MA'] = (df['Open_50_MA'] + df['Close_50_MA']) / 2

df["Volume_50_MA"] = df["Volume"].rolling(window=50).mean()
df.tail()

#Is there a relationship between the moving average of volume and the 50-day moving average?
import matplotlib.pyplot as plt

plt.scatter(df["General_50_MA"], df["Volume_50_MA"])
plt.xlabel("General_50_MA")
plt.ylabel("Volume_50_MA")
plt.title("50 Days Moving Average vs. 50 Days Volume Moving Average")
plt.show()

correlation = df["General_50_MA"].corr(df["Volume_50_MA"])
print(correlation)

"""Two variables tend to move in the opposite direction.
The relationship is not perfect, meaning in some cases two variables can move in the same direction.
Correlation is at the intermediate level, meaning that the movements of the two variables are not always opposite.

"""

correlation_matrix = df.pivot_table(index='Date', columns='Ticker', values='General_50_MA').corr()

# Creating heat map for correlation matrix
plt.figure(figsize=(10, 8))
heatmap = sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', linewidths=.5)

# Date labels on horizontal axis
heatmap.set_xticklabels(heatmap.get_xticklabels(), rotation=45, horizontalalignment='right')

# Equity codes labels on vertical axis
heatmap.set_yticklabels(heatmap.get_yticklabels(), rotation=0)

plt.title('Hisse Senedi Korelasyon Matrisi')

"""**Final Sonuç TR:**
50 günlük hareketli ortalamlara göre yapılan korelasyon matrisi için;
Google ve Microsoft arasında pozitif yönlü çok güçlü bir korelasyon vardır.  
Apple,Google  hisse senetlerinin arasında mükemmel pozitif korelasyon bulunmaktadır.
Apple ve Microsoft arasında pozitif yönlü çok güçlü bir korelasyon vardır.
Netflix'in tüm hisse senetleriyle güçlü negatif bir korelasyonu vardır.

**Analizler doğrultusunda  Apple,Google ve Microsoft hisse senetlerinin aynı yönlü hareket edeceğini söyleyebilirken Netflix'in ise tamamen zıt yönlü hareket edeceğini söyleyebiliriz**

**Final Result ENG: **
For the correlation matrix made according to the 50-day moving averages;

There is a very strong positive correlation between Google and Microsoft.  

There is a perfect positive correlation between Apple and Google stocks.

There is a very strong positive correlation between Apple and Microsoft.

Netflix has a strong negative correlation with all stocks.


**According to the analysis, we can say that Apple, Google and Microsoft stocks will move in the same direction, while Netflix will move in the opposite direction.**
"""